// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mlegposition.proto

package protobuf.demo;

public final class MlegPositionProtos {
  private MlegPositionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MlegPositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.MlegPosition)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */
    int getMoneyMapCount();
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */
    boolean containsMoneyMap(
        int key);
    /**
     * Use {@link #getMoneyMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
    getMoneyMap();
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */
    java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
    getMoneyMapMap();
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    protobuf.demo.MoneyProtos.Money getMoneyMapOrDefault(
        int key,
        protobuf.demo.MoneyProtos.Money defaultValue);
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    protobuf.demo.MoneyProtos.Money getMoneyMapOrThrow(
        int key);

    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    java.util.List<protobuf.demo.MoneyProtos.Money> 
        getMoneyListList();
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    protobuf.demo.MoneyProtos.Money getMoneyList(int index);
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    int getMoneyListCount();
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    java.util.List<? extends protobuf.demo.MoneyProtos.MoneyOrBuilder> 
        getMoneyListOrBuilderList();
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    protobuf.demo.MoneyProtos.MoneyOrBuilder getMoneyListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.MlegPosition}
   */
  public  static final class MlegPosition extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.MlegPosition)
      MlegPositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MlegPosition.newBuilder() to construct.
    private MlegPosition(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MlegPosition() {
      id_ = "";
      moneyList_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MlegPosition(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                moneyMap_ = com.google.protobuf.MapField.newMapField(
                    MoneyMapDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
              moneyMap__ = input.readMessage(
                  MoneyMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              moneyMap_.getMutableMap().put(
                  moneyMap__.getKey(), moneyMap__.getValue());
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                moneyList_ = new java.util.ArrayList<protobuf.demo.MoneyProtos.Money>();
                mutable_bitField0_ |= 0x00000004;
              }
              moneyList_.add(
                  input.readMessage(protobuf.demo.MoneyProtos.Money.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          moneyList_ = java.util.Collections.unmodifiableList(moneyList_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMoneyMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.demo.MlegPositionProtos.MlegPosition.class, protobuf.demo.MlegPositionProtos.MlegPosition.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MONEYMAP_FIELD_NUMBER = 2;
    private static final class MoneyMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, protobuf.demo.MoneyProtos.Money> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, protobuf.demo.MoneyProtos.Money>newDefaultInstance(
                  protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_MoneyMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protobuf.demo.MoneyProtos.Money.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, protobuf.demo.MoneyProtos.Money> moneyMap_;
    private com.google.protobuf.MapField<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
    internalGetMoneyMap() {
      if (moneyMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MoneyMapDefaultEntryHolder.defaultEntry);
      }
      return moneyMap_;
    }

    public int getMoneyMapCount() {
      return internalGetMoneyMap().getMap().size();
    }
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    public boolean containsMoneyMap(
        int key) {
      
      return internalGetMoneyMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMoneyMapMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> getMoneyMap() {
      return getMoneyMapMap();
    }
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    public java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> getMoneyMapMap() {
      return internalGetMoneyMap().getMap();
    }
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    public protobuf.demo.MoneyProtos.Money getMoneyMapOrDefault(
        int key,
        protobuf.demo.MoneyProtos.Money defaultValue) {
      
      java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> map =
          internalGetMoneyMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
     */

    public protobuf.demo.MoneyProtos.Money getMoneyMapOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> map =
          internalGetMoneyMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MONEYLIST_FIELD_NUMBER = 3;
    private java.util.List<protobuf.demo.MoneyProtos.Money> moneyList_;
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    public java.util.List<protobuf.demo.MoneyProtos.Money> getMoneyListList() {
      return moneyList_;
    }
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    public java.util.List<? extends protobuf.demo.MoneyProtos.MoneyOrBuilder> 
        getMoneyListOrBuilderList() {
      return moneyList_;
    }
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    public int getMoneyListCount() {
      return moneyList_.size();
    }
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    public protobuf.demo.MoneyProtos.Money getMoneyList(int index) {
      return moneyList_.get(index);
    }
    /**
     * <code>repeated .proto.Money moneyList = 3;</code>
     */
    public protobuf.demo.MoneyProtos.MoneyOrBuilder getMoneyListOrBuilder(
        int index) {
      return moneyList_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetMoneyMap(),
          MoneyMapDefaultEntryHolder.defaultEntry,
          2);
      for (int i = 0; i < moneyList_.size(); i++) {
        output.writeMessage(3, moneyList_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      for (java.util.Map.Entry<java.lang.Integer, protobuf.demo.MoneyProtos.Money> entry
           : internalGetMoneyMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
        moneyMap__ = MoneyMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, moneyMap__);
      }
      for (int i = 0; i < moneyList_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, moneyList_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.demo.MlegPositionProtos.MlegPosition)) {
        return super.equals(obj);
      }
      protobuf.demo.MlegPositionProtos.MlegPosition other = (protobuf.demo.MlegPositionProtos.MlegPosition) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && internalGetMoneyMap().equals(
          other.internalGetMoneyMap());
      result = result && getMoneyListList()
          .equals(other.getMoneyListList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      if (!internalGetMoneyMap().getMap().isEmpty()) {
        hash = (37 * hash) + MONEYMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMoneyMap().hashCode();
      }
      if (getMoneyListCount() > 0) {
        hash = (37 * hash) + MONEYLIST_FIELD_NUMBER;
        hash = (53 * hash) + getMoneyListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.demo.MlegPositionProtos.MlegPosition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.demo.MlegPositionProtos.MlegPosition prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.MlegPosition}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.MlegPosition)
        protobuf.demo.MlegPositionProtos.MlegPositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMoneyMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMoneyMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.demo.MlegPositionProtos.MlegPosition.class, protobuf.demo.MlegPositionProtos.MlegPosition.Builder.class);
      }

      // Construct using protobuf.demo.MlegPositionProtos.MlegPosition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getMoneyListFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        internalGetMutableMoneyMap().clear();
        if (moneyListBuilder_ == null) {
          moneyList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          moneyListBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.demo.MlegPositionProtos.internal_static_proto_MlegPosition_descriptor;
      }

      @java.lang.Override
      public protobuf.demo.MlegPositionProtos.MlegPosition getDefaultInstanceForType() {
        return protobuf.demo.MlegPositionProtos.MlegPosition.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.demo.MlegPositionProtos.MlegPosition build() {
        protobuf.demo.MlegPositionProtos.MlegPosition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.demo.MlegPositionProtos.MlegPosition buildPartial() {
        protobuf.demo.MlegPositionProtos.MlegPosition result = new protobuf.demo.MlegPositionProtos.MlegPosition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.moneyMap_ = internalGetMoneyMap();
        result.moneyMap_.makeImmutable();
        if (moneyListBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            moneyList_ = java.util.Collections.unmodifiableList(moneyList_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.moneyList_ = moneyList_;
        } else {
          result.moneyList_ = moneyListBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.demo.MlegPositionProtos.MlegPosition) {
          return mergeFrom((protobuf.demo.MlegPositionProtos.MlegPosition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.demo.MlegPositionProtos.MlegPosition other) {
        if (other == protobuf.demo.MlegPositionProtos.MlegPosition.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        internalGetMutableMoneyMap().mergeFrom(
            other.internalGetMoneyMap());
        if (moneyListBuilder_ == null) {
          if (!other.moneyList_.isEmpty()) {
            if (moneyList_.isEmpty()) {
              moneyList_ = other.moneyList_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureMoneyListIsMutable();
              moneyList_.addAll(other.moneyList_);
            }
            onChanged();
          }
        } else {
          if (!other.moneyList_.isEmpty()) {
            if (moneyListBuilder_.isEmpty()) {
              moneyListBuilder_.dispose();
              moneyListBuilder_ = null;
              moneyList_ = other.moneyList_;
              bitField0_ = (bitField0_ & ~0x00000004);
              moneyListBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getMoneyListFieldBuilder() : null;
            } else {
              moneyListBuilder_.addAllMessages(other.moneyList_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.demo.MlegPositionProtos.MlegPosition parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.demo.MlegPositionProtos.MlegPosition) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, protobuf.demo.MoneyProtos.Money> moneyMap_;
      private com.google.protobuf.MapField<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
      internalGetMoneyMap() {
        if (moneyMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MoneyMapDefaultEntryHolder.defaultEntry);
        }
        return moneyMap_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
      internalGetMutableMoneyMap() {
        onChanged();;
        if (moneyMap_ == null) {
          moneyMap_ = com.google.protobuf.MapField.newMapField(
              MoneyMapDefaultEntryHolder.defaultEntry);
        }
        if (!moneyMap_.isMutable()) {
          moneyMap_ = moneyMap_.copy();
        }
        return moneyMap_;
      }

      public int getMoneyMapCount() {
        return internalGetMoneyMap().getMap().size();
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public boolean containsMoneyMap(
          int key) {
        
        return internalGetMoneyMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMoneyMapMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> getMoneyMap() {
        return getMoneyMapMap();
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> getMoneyMapMap() {
        return internalGetMoneyMap().getMap();
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public protobuf.demo.MoneyProtos.Money getMoneyMapOrDefault(
          int key,
          protobuf.demo.MoneyProtos.Money defaultValue) {
        
        java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> map =
            internalGetMoneyMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public protobuf.demo.MoneyProtos.Money getMoneyMapOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> map =
            internalGetMoneyMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMoneyMap() {
        internalGetMutableMoneyMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public Builder removeMoneyMap(
          int key) {
        
        internalGetMutableMoneyMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money>
      getMutableMoneyMap() {
        return internalGetMutableMoneyMap().getMutableMap();
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */
      public Builder putMoneyMap(
          int key,
          protobuf.demo.MoneyProtos.Money value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMoneyMap().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;int32, .proto.Money&gt; moneyMap = 2;</code>
       */

      public Builder putAllMoneyMap(
          java.util.Map<java.lang.Integer, protobuf.demo.MoneyProtos.Money> values) {
        internalGetMutableMoneyMap().getMutableMap()
            .putAll(values);
        return this;
      }

      private java.util.List<protobuf.demo.MoneyProtos.Money> moneyList_ =
        java.util.Collections.emptyList();
      private void ensureMoneyListIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          moneyList_ = new java.util.ArrayList<protobuf.demo.MoneyProtos.Money>(moneyList_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.demo.MoneyProtos.Money, protobuf.demo.MoneyProtos.Money.Builder, protobuf.demo.MoneyProtos.MoneyOrBuilder> moneyListBuilder_;

      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public java.util.List<protobuf.demo.MoneyProtos.Money> getMoneyListList() {
        if (moneyListBuilder_ == null) {
          return java.util.Collections.unmodifiableList(moneyList_);
        } else {
          return moneyListBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public int getMoneyListCount() {
        if (moneyListBuilder_ == null) {
          return moneyList_.size();
        } else {
          return moneyListBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public protobuf.demo.MoneyProtos.Money getMoneyList(int index) {
        if (moneyListBuilder_ == null) {
          return moneyList_.get(index);
        } else {
          return moneyListBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder setMoneyList(
          int index, protobuf.demo.MoneyProtos.Money value) {
        if (moneyListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoneyListIsMutable();
          moneyList_.set(index, value);
          onChanged();
        } else {
          moneyListBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder setMoneyList(
          int index, protobuf.demo.MoneyProtos.Money.Builder builderForValue) {
        if (moneyListBuilder_ == null) {
          ensureMoneyListIsMutable();
          moneyList_.set(index, builderForValue.build());
          onChanged();
        } else {
          moneyListBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder addMoneyList(protobuf.demo.MoneyProtos.Money value) {
        if (moneyListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoneyListIsMutable();
          moneyList_.add(value);
          onChanged();
        } else {
          moneyListBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder addMoneyList(
          int index, protobuf.demo.MoneyProtos.Money value) {
        if (moneyListBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureMoneyListIsMutable();
          moneyList_.add(index, value);
          onChanged();
        } else {
          moneyListBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder addMoneyList(
          protobuf.demo.MoneyProtos.Money.Builder builderForValue) {
        if (moneyListBuilder_ == null) {
          ensureMoneyListIsMutable();
          moneyList_.add(builderForValue.build());
          onChanged();
        } else {
          moneyListBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder addMoneyList(
          int index, protobuf.demo.MoneyProtos.Money.Builder builderForValue) {
        if (moneyListBuilder_ == null) {
          ensureMoneyListIsMutable();
          moneyList_.add(index, builderForValue.build());
          onChanged();
        } else {
          moneyListBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder addAllMoneyList(
          java.lang.Iterable<? extends protobuf.demo.MoneyProtos.Money> values) {
        if (moneyListBuilder_ == null) {
          ensureMoneyListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, moneyList_);
          onChanged();
        } else {
          moneyListBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder clearMoneyList() {
        if (moneyListBuilder_ == null) {
          moneyList_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          moneyListBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public Builder removeMoneyList(int index) {
        if (moneyListBuilder_ == null) {
          ensureMoneyListIsMutable();
          moneyList_.remove(index);
          onChanged();
        } else {
          moneyListBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public protobuf.demo.MoneyProtos.Money.Builder getMoneyListBuilder(
          int index) {
        return getMoneyListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public protobuf.demo.MoneyProtos.MoneyOrBuilder getMoneyListOrBuilder(
          int index) {
        if (moneyListBuilder_ == null) {
          return moneyList_.get(index);  } else {
          return moneyListBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public java.util.List<? extends protobuf.demo.MoneyProtos.MoneyOrBuilder> 
           getMoneyListOrBuilderList() {
        if (moneyListBuilder_ != null) {
          return moneyListBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(moneyList_);
        }
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public protobuf.demo.MoneyProtos.Money.Builder addMoneyListBuilder() {
        return getMoneyListFieldBuilder().addBuilder(
            protobuf.demo.MoneyProtos.Money.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public protobuf.demo.MoneyProtos.Money.Builder addMoneyListBuilder(
          int index) {
        return getMoneyListFieldBuilder().addBuilder(
            index, protobuf.demo.MoneyProtos.Money.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Money moneyList = 3;</code>
       */
      public java.util.List<protobuf.demo.MoneyProtos.Money.Builder> 
           getMoneyListBuilderList() {
        return getMoneyListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protobuf.demo.MoneyProtos.Money, protobuf.demo.MoneyProtos.Money.Builder, protobuf.demo.MoneyProtos.MoneyOrBuilder> 
          getMoneyListFieldBuilder() {
        if (moneyListBuilder_ == null) {
          moneyListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protobuf.demo.MoneyProtos.Money, protobuf.demo.MoneyProtos.Money.Builder, protobuf.demo.MoneyProtos.MoneyOrBuilder>(
                  moneyList_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          moneyList_ = null;
        }
        return moneyListBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.MlegPosition)
    }

    // @@protoc_insertion_point(class_scope:proto.MlegPosition)
    private static final protobuf.demo.MlegPositionProtos.MlegPosition DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.demo.MlegPositionProtos.MlegPosition();
    }

    public static protobuf.demo.MlegPositionProtos.MlegPosition getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MlegPosition>
        PARSER = new com.google.protobuf.AbstractParser<MlegPosition>() {
      @java.lang.Override
      public MlegPosition parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MlegPosition(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MlegPosition> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MlegPosition> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.demo.MlegPositionProtos.MlegPosition getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MlegPosition_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MlegPosition_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MlegPosition_MoneyMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MlegPosition_MoneyMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022mlegposition.proto\022\005proto\032\013money.proto" +
      "\"\257\001\n\014MlegPosition\022\n\n\002id\030\001 \001(\t\0223\n\010moneyMa" +
      "p\030\002 \003(\0132!.proto.MlegPosition.MoneyMapEnt" +
      "ry\022\037\n\tmoneyList\030\003 \003(\0132\014.proto.Money\032=\n\rM" +
      "oneyMapEntry\022\013\n\003key\030\001 \001(\005\022\033\n\005value\030\002 \001(\013" +
      "2\014.proto.Money:\0028\001B#\n\rprotobuf.demoB\022Mle" +
      "gPositionProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protobuf.demo.MoneyProtos.getDescriptor(),
        }, assigner);
    internal_static_proto_MlegPosition_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_MlegPosition_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MlegPosition_descriptor,
        new java.lang.String[] { "Id", "MoneyMap", "MoneyList", });
    internal_static_proto_MlegPosition_MoneyMapEntry_descriptor =
      internal_static_proto_MlegPosition_descriptor.getNestedTypes().get(0);
    internal_static_proto_MlegPosition_MoneyMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MlegPosition_MoneyMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protobuf.demo.MoneyProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
