// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wallet.proto

package protobuf.demo;

public final class WalletProtos {
  private WalletProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WalletOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Wallet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string balance = 1;</code>
     */
    java.lang.String getBalance();
    /**
     * <code>string balance = 1;</code>
     */
    com.google.protobuf.ByteString
        getBalanceBytes();

    /**
     * <code>.proto.Wallet.WalletType type = 2;</code>
     */
    int getTypeValue();
    /**
     * <code>.proto.Wallet.WalletType type = 2;</code>
     */
    protobuf.demo.WalletProtos.Wallet.WalletType getType();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>bool isNameNull = 4;</code>
     */
    boolean getIsNameNull();
  }
  /**
   * Protobuf type {@code proto.Wallet}
   */
  public  static final class Wallet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Wallet)
      WalletOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Wallet.newBuilder() to construct.
    private Wallet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wallet() {
      balance_ = "";
      type_ = 0;
      name_ = "";
      isNameNull_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Wallet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              balance_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 32: {

              isNameNull_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protobuf.demo.WalletProtos.internal_static_proto_Wallet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protobuf.demo.WalletProtos.internal_static_proto_Wallet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protobuf.demo.WalletProtos.Wallet.class, protobuf.demo.WalletProtos.Wallet.Builder.class);
    }

    /**
     * Protobuf enum {@code proto.Wallet.WalletType}
     */
    public enum WalletType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ALIPAY = 0;</code>
       */
      ALIPAY(0),
      /**
       * <code>WECHAT = 1;</code>
       */
      WECHAT(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>ALIPAY = 0;</code>
       */
      public static final int ALIPAY_VALUE = 0;
      /**
       * <code>WECHAT = 1;</code>
       */
      public static final int WECHAT_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WalletType valueOf(int value) {
        return forNumber(value);
      }

      public static WalletType forNumber(int value) {
        switch (value) {
          case 0: return ALIPAY;
          case 1: return WECHAT;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<WalletType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          WalletType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<WalletType>() {
              public WalletType findValueByNumber(int number) {
                return WalletType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return protobuf.demo.WalletProtos.Wallet.getDescriptor().getEnumTypes().get(0);
      }

      private static final WalletType[] VALUES = values();

      public static WalletType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private WalletType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:proto.Wallet.WalletType)
    }

    public static final int BALANCE_FIELD_NUMBER = 1;
    private volatile java.lang.Object balance_;
    /**
     * <code>string balance = 1;</code>
     */
    public java.lang.String getBalance() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        balance_ = s;
        return s;
      }
    }
    /**
     * <code>string balance = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBalanceBytes() {
      java.lang.Object ref = balance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        balance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.proto.Wallet.WalletType type = 2;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.proto.Wallet.WalletType type = 2;</code>
     */
    public protobuf.demo.WalletProtos.Wallet.WalletType getType() {
      @SuppressWarnings("deprecation")
      protobuf.demo.WalletProtos.Wallet.WalletType result = protobuf.demo.WalletProtos.Wallet.WalletType.valueOf(type_);
      return result == null ? protobuf.demo.WalletProtos.Wallet.WalletType.UNRECOGNIZED : result;
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISNAMENULL_FIELD_NUMBER = 4;
    private boolean isNameNull_;
    /**
     * <code>bool isNameNull = 4;</code>
     */
    public boolean getIsNameNull() {
      return isNameNull_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBalanceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, balance_);
      }
      if (type_ != protobuf.demo.WalletProtos.Wallet.WalletType.ALIPAY.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (isNameNull_ != false) {
        output.writeBool(4, isNameNull_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBalanceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, balance_);
      }
      if (type_ != protobuf.demo.WalletProtos.Wallet.WalletType.ALIPAY.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (isNameNull_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isNameNull_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protobuf.demo.WalletProtos.Wallet)) {
        return super.equals(obj);
      }
      protobuf.demo.WalletProtos.Wallet other = (protobuf.demo.WalletProtos.Wallet) obj;

      boolean result = true;
      result = result && getBalance()
          .equals(other.getBalance());
      result = result && type_ == other.type_;
      result = result && getName()
          .equals(other.getName());
      result = result && (getIsNameNull()
          == other.getIsNameNull());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BALANCE_FIELD_NUMBER;
      hash = (53 * hash) + getBalance().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ISNAMENULL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsNameNull());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.demo.WalletProtos.Wallet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protobuf.demo.WalletProtos.Wallet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protobuf.demo.WalletProtos.Wallet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protobuf.demo.WalletProtos.Wallet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Wallet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Wallet)
        protobuf.demo.WalletProtos.WalletOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protobuf.demo.WalletProtos.internal_static_proto_Wallet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protobuf.demo.WalletProtos.internal_static_proto_Wallet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protobuf.demo.WalletProtos.Wallet.class, protobuf.demo.WalletProtos.Wallet.Builder.class);
      }

      // Construct using protobuf.demo.WalletProtos.Wallet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        balance_ = "";

        type_ = 0;

        name_ = "";

        isNameNull_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protobuf.demo.WalletProtos.internal_static_proto_Wallet_descriptor;
      }

      @java.lang.Override
      public protobuf.demo.WalletProtos.Wallet getDefaultInstanceForType() {
        return protobuf.demo.WalletProtos.Wallet.getDefaultInstance();
      }

      @java.lang.Override
      public protobuf.demo.WalletProtos.Wallet build() {
        protobuf.demo.WalletProtos.Wallet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public protobuf.demo.WalletProtos.Wallet buildPartial() {
        protobuf.demo.WalletProtos.Wallet result = new protobuf.demo.WalletProtos.Wallet(this);
        result.balance_ = balance_;
        result.type_ = type_;
        result.name_ = name_;
        result.isNameNull_ = isNameNull_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protobuf.demo.WalletProtos.Wallet) {
          return mergeFrom((protobuf.demo.WalletProtos.Wallet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protobuf.demo.WalletProtos.Wallet other) {
        if (other == protobuf.demo.WalletProtos.Wallet.getDefaultInstance()) return this;
        if (!other.getBalance().isEmpty()) {
          balance_ = other.balance_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getIsNameNull() != false) {
          setIsNameNull(other.getIsNameNull());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protobuf.demo.WalletProtos.Wallet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protobuf.demo.WalletProtos.Wallet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object balance_ = "";
      /**
       * <code>string balance = 1;</code>
       */
      public java.lang.String getBalance() {
        java.lang.Object ref = balance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          balance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string balance = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBalanceBytes() {
        java.lang.Object ref = balance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          balance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string balance = 1;</code>
       */
      public Builder setBalance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        balance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 1;</code>
       */
      public Builder clearBalance() {
        
        balance_ = getDefaultInstance().getBalance();
        onChanged();
        return this;
      }
      /**
       * <code>string balance = 1;</code>
       */
      public Builder setBalanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        balance_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.proto.Wallet.WalletType type = 2;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.proto.Wallet.WalletType type = 2;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Wallet.WalletType type = 2;</code>
       */
      public protobuf.demo.WalletProtos.Wallet.WalletType getType() {
        @SuppressWarnings("deprecation")
        protobuf.demo.WalletProtos.Wallet.WalletType result = protobuf.demo.WalletProtos.Wallet.WalletType.valueOf(type_);
        return result == null ? protobuf.demo.WalletProtos.Wallet.WalletType.UNRECOGNIZED : result;
      }
      /**
       * <code>.proto.Wallet.WalletType type = 2;</code>
       */
      public Builder setType(protobuf.demo.WalletProtos.Wallet.WalletType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.proto.Wallet.WalletType type = 2;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private boolean isNameNull_ ;
      /**
       * <code>bool isNameNull = 4;</code>
       */
      public boolean getIsNameNull() {
        return isNameNull_;
      }
      /**
       * <code>bool isNameNull = 4;</code>
       */
      public Builder setIsNameNull(boolean value) {
        
        isNameNull_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool isNameNull = 4;</code>
       */
      public Builder clearIsNameNull() {
        
        isNameNull_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Wallet)
    }

    // @@protoc_insertion_point(class_scope:proto.Wallet)
    private static final protobuf.demo.WalletProtos.Wallet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protobuf.demo.WalletProtos.Wallet();
    }

    public static protobuf.demo.WalletProtos.Wallet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wallet>
        PARSER = new com.google.protobuf.AbstractParser<Wallet>() {
      @java.lang.Override
      public Wallet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Wallet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wallet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Wallet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public protobuf.demo.WalletProtos.Wallet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Wallet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Wallet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014wallet.proto\022\005proto\"\211\001\n\006Wallet\022\017\n\007bala" +
      "nce\030\001 \001(\t\022&\n\004type\030\002 \001(\0162\030.proto.Wallet.W" +
      "alletType\022\014\n\004name\030\003 \001(\t\022\022\n\nisNameNull\030\004 " +
      "\001(\010\"$\n\nWalletType\022\n\n\006ALIPAY\020\000\022\n\n\006WECHAT\020" +
      "\001B\035\n\rprotobuf.demoB\014WalletProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Wallet_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Wallet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Wallet_descriptor,
        new java.lang.String[] { "Balance", "Type", "Name", "IsNameNull", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
